Câu 1:

In [11]:
# Numpy code
import numpy as np
arr_arange=np.arange(10)
print(arr_arange)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Pytorch code
import torch
tensor_arange=torch.arange(10)
print(tensor_arange)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
# TensorFlow code
import tensorflow as tf
tensor_arange=tf.range(10)
print(tensor_arange)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


Câu 2:

In [14]:
# Numpy code
arr_eye=np.eye(3,3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Pytorch ode
tensor_eye=torch.eye(3,3)
print(tensor_eye)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [16]:
# TensorFlow code
tensor_eye=tf.eye(3,3)
print(tensor_eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


Câu 3:

In [42]:
# Numpy code
np.random.seed(2024)
arr_rand=np.random.rand(3,4)
print('Mảng ngẫu nhiên trong khoảng [0,1):\n',arr_rand)
print()
arr_randint=np.random.randint(-10,10,size=(3,4))
print('Mảng ngẫu nhiên trong khoảng [-10,10):\n',arr_randint)

Mảng ngẫu nhiên trong khoảng [0,1):
 [[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]

Mảng ngẫu nhiên trong khoảng [-10,10):
 [[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]


In [55]:
# Pytorch code
torch.manual_seed(2024)
tensor_rand=torch.rand(3,4)
print('Tensor ngẫu nhiên trong khoảng [0,1):\n',tensor_rand)
print()
tensor_randint=torch.randint(-10,10,size=(3,4))
print('Tensor ngẫu nhiên trong khoảng [-10,10):\n',tensor_randint)

Tensor ngẫu nhiên trong khoảng [0,1):
 tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])

Tensor ngẫu nhiên trong khoảng [-10,10):
 tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])


In [54]:
# TensorFlow code
tf.random.set_seed(2024)
tensor_rand=tf.random.uniform((3,4))
print('Tensor ngẫu nhiên trong khoảng [0,1):\n',tensor_rand)
print()
tensor_randint=tf.random.uniform((3,4),minval=-10,maxval=10,dtype=tf.dtypes.int32)
print('Tensor ngẫu nhiên trong khoảng [-10,10):\n',tensor_randint)


Tensor ngẫu nhiên trong khoảng [0,1):
 tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)

Tensor ngẫu nhiên trong khoảng [-10,10):
 tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
