DANH SÁCH 1 CHIỀU

In [1]:
import numpy as np
import torch
import tensorflow as tf

list_1D=[1,2,3,4,5,6,7,8,9]

arr_1D=np.array(list_1D)

tensor_1D_pt=torch.tensor(list_1D)

tensor_1D_tf=tf.convert_to_tensor(list_1D)

print("Mảng 1 chiều của Numpy:",arr_1D,type(arr_1D),sep='\n')
print()
print("Tensor Pytorch 1 chiều:",arr_1D,type(arr_1D),sep='\n',end='\n')
print()
print("Tensor Tensorflow 1 chiều:",arr_1D,type(arr_1D),sep='\n')

Mảng 1 chiều của Numpy:
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>

Tensor Pytorch 1 chiều:
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>

Tensor Tensorflow 1 chiều:
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


DANH SÁCH 2 CHIỀU

In [2]:
list_2D=[[1,2,3],[4,5,6],[7,8,9]]
arr_2D=np.array(list_2D)
tensor_2D_pt=torch.tensor(list_2D)
tensor_2D_tf=tf.convert_to_tensor(list_2D)  
# Numpy
print('Hình dạng của mảng 2 chiều:',arr_2D.shape)
print()
print('Kiểu dữ liệu của mảng:',arr_2D.dtype)
print()
print('Loại của mảng:',type(arr_2D))
print()
print('Mảng:\n',(arr_2D))
print()

Hình dạng của mảng 2 chiều: (3, 3)

Kiểu dữ liệu của mảng: int32

Loại của mảng: <class 'numpy.ndarray'>

Mảng:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



In [3]:
# Pytorch
print('Hình dạng của tensor 2 chiều:',tensor_2D_pt.shape)
print()
print('Kiểu dữ liệu của tensor 2 chiều:',tensor_2D_pt.dtype)
print()
print('Loại của tensor 2 chiều:',type(tensor_2D_pt))
print()
print('Thiết bị lữu trữ của tensor:',tensor_2D_pt.device)
print()
print('Tensor:\n',(arr_2D))

Hình dạng của tensor 2 chiều: torch.Size([3, 3])

Kiểu dữ liệu của tensor 2 chiều: torch.int64

Loại của tensor 2 chiều: <class 'torch.Tensor'>

Thiết bị lữu trữ của tensor: cpu

Tensor:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Tensorflow
print('Hình dạng của tensor 2 chiều:',tensor_2D_tf.shape)
print()
print('Kiểu dữ liệu của tensor:',tensor_2D_tf.dtype)
print()
print('Loại của tensor 2 chiều:',type(tensor_2D_tf))
print()
print('Thiết bị lữu trữ của tensor:',tensor_2D_tf.device)
print()
print('Tensor:\n',(tensor_2D_tf))

Hình dạng của tensor 2 chiều: (3, 3)

Kiểu dữ liệu của tensor: <dtype: 'int32'>

Loại của tensor 2 chiều: <class 'tensorflow.python.framework.ops.EagerTensor'>

Thiết bị lữu trữ của tensor: /job:localhost/replica:0/task:0/device:CPU:0

Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
